{% set name = "black" %}
{% set version = "19.10b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2edb73a08e9e0e6f65a0e6af18b059b8b1cdd5bef997d7a0b181df93dc81539

build:
  number: 2
  noarch: python
  entry_points:
    - black = black:patched_main
    - blackd = blackd:patched_main

test:
  commands:
    - black --help

outputs:
  - name: {{ name }}
    script: build_base.sh
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools_scm
      run:
        - python >=3.6
        - click >=6.5
        - attrs >=18.1.0
        - appdirs
        - toml >=0.9.4
        - typed-ast >=1.4.0
        - regex
        - pathspec >=0.6,<1
  
  - name: {{ name }}d
    requirements:
      run:
        - {{ pin_subpackage('black', exact=True) }}
        - aiohttp >=3.3.2
        - aiohttp-cors
    test:
      commands:
        - blackd --help

about:
  home: https://github.com/python/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The Uncompromising Code Formatter'

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://github.com/python/black
  dev_url: https://github.com/python/black

extra:
  recipe-maintainers:
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
