{% set name = "black" %}
{% set version = "25.1.0" %}

package:
  name: black-recipe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/black/black-{{ version }}.tar.gz
  sha256: 33496d5cd1222ad73391352b4ae8da15253c5de89b93a80b3e2c8d9a19ec2666

build:
  number: 0

outputs:
  - name: black
    script: build_base.sh
    build:
      noarch: python
      entry_points:
        - black = black:patched_main
        - blackd = blackd:patched_main
    requirements:
      host:
        - python >=3.11                     # [not py_lt_311]
        - python {{ python_min }}           # [py_lt_311]
        - pip
        - hatchling >=1.8.0
        - hatch-vcs
        - hatch-fancy-pypi-readme
      run:
        - click >=8.0.0
        - platformdirs >=2
        - packaging >=22.0
        - pathspec >=0.9
        - mypy_extensions >=0.4.3
        - tomli >=1.1.0                     # [py_lt_311]
        - typing_extensions >=4.0.1         # [py_lt_311]
        - python >={{ python_min }},<3.11   # [py_lt_311]
        - python >=3.11                     # [not py_lt_311]
    test:
      requires:
        - python {{ python_min }}           # [py_lt_311]
        - python 3.11                       # [not py_lt_311]
        - pip
      commands:
        - black --help
        - pip check
        - which blackd || where blackd

  - name: blackd
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('black', max_pin='x.x.x') }}
        - aiohttp >=3.10
    test:
      requires:
        - python {{ python_min }}    # [py_lt_311]
        - python 3.11                # [not py_lt_311]
      commands:
        - black --help
        - blackd --help

  - name: black-colorama
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('black', max_pin='x.x.x') }}
        - colorama >=0.4.3
    test:
      requires:
        - python {{ python_min }}    # [py_lt_311]
        - python 3.11                # [not py_lt_311]
      commands:
        - black --help

  - name: black-jupyter
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('black', max_pin='x.x.x') }}
        - ipython >=7.8.0
        - tokenize-rt >=3.2.0
    test:
      requires:
        - python {{ python_min }}    # [py_lt_311]
        - python 3.11                # [not py_lt_311]
      commands:
        - black --help
        - python -c "import black.handle_ipynb_magics; assert black.handle_ipynb_magics.jupyter_dependencies_are_installed(warn=True) == True"

about:
  home: https://github.com/psf/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The uncompromising code formatter.

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://black.readthedocs.io/
  dev_url: https://github.com/psf/black

extra:
  recipe-maintainers:
    - raybellwaves
    - seanlaw
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
