{% set name = "black" %}
{% set version = "23.3.0" %}

package:
  name: {{ name|lower }}-recipe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c7b8d606e728a41ea1ccbd7264677e494e87cf630e399262ced92d4a8dac940

build:
  number: 1

outputs:
  - name: {{ name }}
    script: build_base.sh
    build:
      skip: true  # [py<36]
      entry_points:
        - black = black:patched_main
        - blackd = blackd:patched_main
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - hatchling>=1.8.0
        - hatch-vcs
        - hatch-fancy-pypi-readme
      run:
        - python
        - click >=8.0.0
        - platformdirs >=2
        - packaging >=22.0
        - tomli >=1.1.0  # [py<311]
        - typed-ast >=1.4.2  # [py<38]
        - pathspec >=0.9
        - typing_extensions >=3.10  # [py<310]
        - mypy_extensions >=0.4.3
    test:
      requires:
        - pip
      commands:
        - black --help
        - pip check
        - which blackd || where blackd

  - name: {{ name }}d
    build:
      noarch: python
      # Skip this package for cross-builds. We will only need a single upload anyways
      skip: true  # [not linux64]
    requirements:
      run:
        - {{ pin_subpackage('black', max_pin='x.x.x') }}
        - aiohttp >=3.7.4
    test:
      commands:
        - black --help
        - blackd --help

  - name: {{ name }}-colorama
    build:
      noarch: python
      # Skip this package for cross-builds. We will only need a single upload anyways
      skip: true  # [not linux64]
    requirements:
      run:
        - {{ pin_subpackage('black', max_pin='x.x.x') }}
        - colorama  >=0.4.3
    test:
      commands:
        - black --help

  - name: {{ name }}-jupyter
    build:
      noarch: python
      # Skip this package for cross-builds. We will only need a single upload anyways
      skip: true  # [not linux64]
    requirements:
      run:
        - {{ pin_subpackage('black', max_pin='x.x.x') }}
        - ipython >=7.8.0
        - tokenize-rt >=3.2.0
    test:
      commands:
        - black --help
        - python -c "import black.handle_ipynb_magics; assert black.handle_ipynb_magics.jupyter_dependencies_are_installed(verbose=True, quiet=False) == True"

about:
  home: https://github.com/psf/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The uncompromising code formatter.

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://black.readthedocs.io/
  dev_url: https://github.com/psf/black

extra:
  recipe-maintainers:
    - raybellwaves
    - seanlaw
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
